- name: Common | Ping data nodes before doing anything else
  hosts: data_node
  gather_facts: false
  tasks:
    - ping: "{{inventory_hostname}}"

- name: Installer | Slice nodes into OS groups
  hosts: data_node
  tasks:
     - group_by: key=os_{{ ansible_distribution }}_{{ ansible_distribution_major_version }}

- name: Common | Remove containers
  hosts: data_node
  roles:
    - common_purge_containers

- name: Common | Cleanup Common items
  hosts: data_node
  roles:
    - common_purge_cleanup

#- name: CentOS 7 | Cleanup OS-specific items
#  hosts: data_node:&os_CentOS_7
#  roles:
#    - CentOS_7_purge
