- name: "Common | Create custom facts directory"
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"

- name: "Common | Insert data_node.fact file"
  template:
    src: data_node.fact.j2
    dest: /etc/ansible/facts.d/data_node.fact
    mode: 0755

- name: "Common | Reload facts to pick up new items"
  setup: ~
